# -*- coding: utf-8 -*-
"""Simulador_de_ChatBot_Automotivo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvNtfd3Hp5NPkaD5AsUAoUKqyeczydaT

#Simulador de ChatBot com GenAI e VectorDB

Este projeto apresenta um assistente virtual para a iAutos capaz de tirar dúvidas sobre regras, fraudes e anúncios. O Chatbot combina busca semântica em documentos PDF para questões complexas e regras de negócio pré-definidas para perguntas sobre valores de veículos, garantindo que o usuário receba sempre a informação correta, seja ela extraída do manual ou uma diretriz da plataforma.

Desenvolvimento:
"""

# Instalação das bibliotecas necessárias
!pip install langchain langchain-openai langchain-community chromadb pypdf unstructured -q

print("Bibliotecas instaladas com sucesso!")

# Importação das bibliotecas

from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings
import os
from google.colab import userdata

# Configuração segura das credenciais
os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

# Variáveis de configuração para os modelos
LLM_DEPLOYMENT_MODEL = userdata.get('LLM_DEPLOYMENT_MODEL')
LLM_API_VERSION = userdata.get('LLM_API_VERSION')
EMB_DEPLOYMENT_MODEL = userdata.get('EMB_DEPLOYMENT_MODEL')
EMB_API_VERSION = userdata.get('EMB_API_VERSION')

# E na sua inicialização do LLM/Embedding, use as variáveis de ambiente
# (O LangChain faz isso automaticamente se você definir as variáveis de ambiente)

# Exemplo para a FUNÇÃO 3 e 4:
embeddings = AzureOpenAIEmbeddings(
    azure_deployment=EMB_DEPLOYMENT_MODEL,
    openai_api_version=EMB_API_VERSION

)

llm = AzureChatOpenAI(
    azure_deployment=LLM_DEPLOYMENT_MODEL,
    openai_api_version=LLM_API_VERSION,
    temperature=0.3

)

#  Bibliotecas Importações Corrigidas
import langchain

# 1. Modelos (LLM e Embedding)
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings

# 2. Componentes Comunitários (Loaders, Vectorstores)
from langchain.memory import ConversationBufferMemory
from langchain_community.vectorstores import Chroma

# 3. Componentes de Divisão de Texto (Text Splitter)
from langchain_text_splitters import RecursiveCharacterTextSplitter

# 4. Componentes Chave Refatorados (AJUSTADO):
# Chain volta para o módulo principal, onde geralmente fica:
from langchain.chains import ConversationalRetrievalChain #De volta ao 'langchain.chains'
# Memory e Prompts/Schema permanecem no Core ou Community:
from langchain.memory import ConversationBufferMemory
from langchain_core.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
    MessagesPlaceholder
)
from langchain_core.documents import Document

# importando as bibliotecas para Azure
from langchain_openai import AzureChatOpenAI
from langchain_openai import AzureOpenAIEmbeddings
from langchain_community.vectorstores import DocArrayInMemorySearch
from langchain.chains import RetrievalQA
from langchain_core.documents import Document

#  Imports necessários para esta célula
import langchain
import os
from google.colab import userdata
from langchain_openai import AzureChatOpenAI

# Ativa logs de debug
flg_log_debug = False
langchain.debug = flg_log_debug

# --- Configuração Segura (Usando Secrets) ---
# O LangChain vai ler as chaves do ambiente automaticamente
os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

# --- Configurações Corretas do Modelo de CHAT ---
# Pegamos o nome do deployment do LLM (ex: "gpt-4.1") dos seus secrets
LLM_CHAT_DEPLOYMENT_NAME = userdata.get('LLM_DEPLOYMENT_MODEL')
LLM_CHAT_API_VERSION = userdata.get('LLM_API_VERSION')

# --- Inicializa o modelo de CHAT (LLM) via Azure ---
llm = AzureChatOpenAI(
    # O endpoint e a api_key já foram lidos das variáveis de ambiente
    deployment_name = LLM_CHAT_DEPLOYMENT_NAME,
    openai_api_version = LLM_CHAT_API_VERSION,
    temperature = 0.5,
    verbose = flg_log_debug
)

print("✅ Modelo LLM (AzureChatOpenAI) inicializado com sucesso!")

# Download do arquivo de contexto
import os
import gdown

# 1. ID do arquivo no Google Drive
file_id = "1-ZpUOl8OA4lxa8CJ6auT42hSxaF3jclk"

#https://drive.google.com/file/d/1-ZpUOl8OA4lxa8CJ6auT42hSxaF3jclk
# 2. Nome do arquivo local
local_filename = "Caso de uso - Marketplace de classificados veículos.pdf"

# 3. Baixa o arquivo do Google Drive para a sessão local
gdown.download(f"https://drive.google.com/uc?id={file_id}", local_filename, quiet=False)

# Loader específico para PDF
from langchain_community.document_loaders import PyPDFLoader

# O pacote PyPDFLoader é específico para PDF
arquivo_pdf = local_filename
loader = PyPDFLoader(arquivo_pdf)

# Carregando o contexto do PDF
documents_pdf = loader.load()
## O loader já retorna a lista de Document (um por página do PDF)

# Quantidade de páginas
len(documents_pdf)

print(f"O PDF possui {len(documents_pdf)} páginas.")

# Extract text content from the loaded PDF documents
text_content = ""
for doc in documents_pdf:
    text_content += doc.page_content + "\n"

# Split the text into chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1000,
    chunk_overlap = 200,
    length_function = len,
)

chunks = text_splitter.split_text(text_content)

# Convert the text chunks back to Document objects
documents = [Document(page_content=t) for t in chunks]

print(f"O contexto foi dividido em {len(chunks)} documentos (chunks).")

# Importação das Bibliotecas (Versão Azure) ---

print("Importando as bibliotecas necessárias (Versão Azure)...")

# --- Bibliotecas de Preparação de Dados (Nível 2) ---
from langchain_community.document_loaders import PyPDFLoader # Para carregar o PDF
from langchain.text_splitter import RecursiveCharacterTextSplitter # Para dividir o texto em pedaços (chunks)
# -----------------------------------------------------------------
# Usando o modelo de Embedding específico do Azure
from langchain_openai import AzureOpenAIEmbeddings # Para transformar texto em vetores (números)
# -----------------------------------------------------------------
from langchain_community.vectorstores import Chroma # O banco de dados vetorial

# --- Bibliotecas do Chatbot (Nível 3) ---
# -----------------------------------------------------------------
# Usando o modelo de Chat específico do Azure
from langchain_openai import AzureChatOpenAI # O "cérebro" do chatbot (LLM)
# -----------------------------------------------------------------
from langchain.chains import ConversationalRetrievalChain # A lógica que conecta tudo (pergunta + vetores + LLM)

print("✅ Todas as bibliotecas (Versão Azure) foram importadas!")

# Processamento de Chunks e Criação do VectorDB
import os
from google.colab import userdata

print("Iniciando a criação do VectorDB (Versão Azure)...")

# --- Configuração Segura (Usando Secrets) ---
# Define as variáveis de ambiente que o LangChain procura
os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

# 1. Inicializando o modelo de embedding (lendo secrets automaticamente)
print("   Inicializando o modelo de embedding (AzureOpenAIEmbeddings)...")
embeddings = AzureOpenAIEmbeddings(
    azure_deployment=userdata.get('EMB_DEPLOYMENT_MODEL'),
    openai_api_version=userdata.get('EMB_API_VERSION')
)

# 2. "Purificação" dos dados (Chunks)
# (Assumindo que a variável 'chunks' foi definida na célula anterior)
print(f"   Filtrando os {len(chunks)} chunks (removendo nulos ou vazios)...")

chunk_texts = [
    doc.page_content for doc in documents
    if doc.page_content is not None and doc.page_content.strip() != ""
]
print(f"   ... {len(chunks)} chunks originais filtrados em {len(chunk_texts)} chunks de texto válidos.")

# 3. Criação do VectorDB (ChromaDB)
print("   Criando o VectorDB (usando Chroma.from_texts)...")
vectordb = Chroma.from_texts(
    texts=chunk_texts,    # Nossa lista de texto puro
    embedding=embeddings  # O modelo de embedding da AZURE
)

print("\n✅ VectorDB (Vectordb) criado com sucesso!")
print("   O 'vectordb' está pronto para ser consultado.")
print("\n PREPARAÇÃO DE DADOS CONCLUÍDA ---")

#  Criação da Cadeia (Chain) Conversacional
import os
from google.colab import userdata
from langchain.chains import ConversationalRetrievalChain
from langchain_openai import AzureChatOpenAI

print("Iniciando a criação do ChatBot (ConversationalRetrievalChain)...")

# --- Configuração Segura (Usando Secrets) ---
# Define as variáveis de ambiente que o LangChain procura
os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

# 1. Inicializando o "Cérebro" (AzureChatOpenAI)
print("   Inicializando o modelo de LLM (AzureChatOpenAI)...")
llm = AzureChatOpenAI(
    # Endpoint e Chave são lidos automaticamente das variáveis de ambiente
    azure_deployment=userdata.get('LLM_DEPLOYMENT_MODEL'), # Pega o deployment de CHAT
    openai_api_version=userdata.get('LLM_API_VERSION'),    # Pega a versão da API de CHAT
    temperature=0.3
)

# 2. Criando a Cadeia (Chain) que conecta os componentes
print("   Criando a ConversationalRetrievalChain...")
# (Assumindo que 'vectordb' foi criado na célula anterior)
qa_chain = ConversationalRetrievalChain.from_llm(
    llm,
    retriever=vectordb.as_retriever() # Conecta a cadeia ao nosso VectorDB
)

print("\n✅ CHATBOT CRIADO! (qa_chain)")
print("   O chatbot está pronto para receber perguntas.")
print("\n CRIAÇÃO DA CADEIA CONCLUÍDA ---")

# CONFIGURAÇÃO DO CONECTOR E ROTEADOR
from langchain.chains import ConversationalRetrievalChain

DEFAULT_FALLBACK = (
    "Desculpe, a informação exata sobre este tópico não está detalhada "
    "nas Políticas de Uso da iAutos que eu tenho acesso."
)

# Criação da chain principal
qa_chain = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=vectordb.as_retriever(search_kwargs={"k": 3}),
    return_source_documents=False
)

# --- Função de roteamento inteligente ---
def handle_query(query):
    """
    Direciona a pergunta para o lugar certo.
    """
    q_lower = query.lower()

    # Detecta temas fora do escopo
    if any(palavra in q_lower for palavra in ["preço", "valor", "quanto custa", "gol", "caro", "barato"]):
        return "A iAutos não define preços de veículos. Os valores variam conforme os anúncios de vendedores. Consulte a barra de busca da plataforma para ver os preços atualizados."

    # Se for dúvida sobre políticas, envia ao modelo
    result = qa_chain.invoke({"question": query, "chat_history": []})
    return result["answer"]

print("✅✅✅ CONECTOR CRIADO E ROTEADOR ATIVO!")

# BATERIA DE TESTES AUTOMÁTICOS
def run_pipeline_tests(verbose=True):
    tests = [
        {"query": "O que é a iAutos?", "expect_contains": ["marketplace", "classificados", "iAutos"]},
        {"query": "Quais são os tipos de veículos permitidos?", "expect_contains": ["automóveis", "motos", "utilitários"]},
        {"query": "Qual o preço de um Gol?", "expect_contains": ["não define preços", "anúncios", "valores variam"]},  # <- Novo teste
        {"query": "Como eu entro em contato com o vendedor?", "expect_contains": ["contato", "vendedor", "mensagem"]},
        {"query": "O que acontece se eu fraudar?", "expect_contains": ["banido", "banimento", "fraudar"]}
    ]

    passed, failed = 0, 0
    details = []

    print("\n--- 🧪 Iniciando Bateria de Testes Automáticos ---\n")

    for t in tests:
        q = t["query"]
        try:
            ans = handle_query(q)
            ans_lower = ans.lower()
            expected = any(word in ans_lower for word in t["expect_contains"])

            if expected:
                passed += 1
                status = "✅ PASSOU"
            else:
                failed += 1
                status = "❌ FALHOU"

            print(f"[{status}] Pergunta: {q}\n--> Resposta: {ans[:100]}...\n")
            details.append({"query": q, "status": status, "answer_sample": ans[:100]})

        except Exception as e:
            failed += 1
            print(f"[ERRO] Pergunta: {q} -> {e}\n")
            details.append({"query": q, "status": "ERRO", "error": str(e)})

    print(f"--- 🏁 Resumo dos Testes ---")
    print(f"✅ Passou: {passed} | ❌ Falhou: {failed}\n")
    return passed, failed, details

# --- Executa ---
run_pipeline_tests()

!pip install gradio -q

# (Certifique-se de que a célula anterior, que define 'qa_chain', já foi executada)

import gradio as gr

def interface_chatbot_robusta(message, history):
    """
    Esta é a função que o Gradio vai chamar.
    Ela usa EXATAMENTE a mesma lógica do seu loop 'simular_conversa'.
    """

    # 1. O ROTEADOR (que lida com o "Gol")
    q_lower = message.lower()
    if any(palavra in q_lower for palavra in ["preço", "valor", "quanto custa", "gol", "caro", "barato"]):

        # Ação A: Resposta padrão
        return "A iAutos não define preços de veículos. Os valores variam conforme os anúncios de vendedores. Consulte a barra de busca da plataforma para ver os preços atualizados."

    else:
        # Ação B: Chama o RAG (qa_chain)
        # A 'qa_chain' já tem memória interna, então não precisamos passar o 'history'
        result = qa_chain.invoke({"question": message})
        return result["answer"]

# --- FIM DA LÓGICA ---


# 2. CRIAR E LANÇAR A PÁGINA
print("Iniciando a página de teste interativa...")
print("Aguarde o link público (.gradio.live) aparecer...")

demo_chat = gr.ChatInterface(
    fn=interface_chatbot_robusta,   # A função que acabamos de criar
    title="🤖 iAutos ChatBot (Versão Robusta)",
    description="Teste o bot com perguntas de política ('fraude') ou fora do escopo ('preço do Gol').",
    examples=["O que é a iAutos?", "O que acontece se eu fraudar?", "Qual o preço de um Gol?"],
    chatbot=gr.Chatbot(height=500)
)

# 3. INICIAR (share=True cria um link público temporário)
demo_chat.launch(share=True)

#  Interrogar o chatbot (O Teste de Batalha) ---

flg_log_debug = False
langchain.debug = flg_log_debug

print("O Chatbot está pronto. Faça suas perguntas sobre o PDF da iAutos.")
print("Digite 'sair' a qualquer momento para encerrar o teste.")

# O Chatbot precisa de uma "memória de curto prazo" (uma lista vazia)
chat_history = []

while True:
    # 1.  (você) faz a pergunta
    query = input("\n[VOCÊ]: ")

    # 2. Condição de Saída
    if query.lower() == 'sair':
        print("\n[CHATBOT]: Até logo! Obrigado por usar a iAutos.")
        break
    # 3. O Chatbot "pensa"
    #    Ele usa a 'query' (pergunta) e a 'chat_history' (memória)
    result = qa_chain.invoke({"question": query, "chat_history": chat_history})

    # 4. O Chatbot "lembra" (atualiza a memória)
    chat_history.append((query, result["answer"]))

    # 5. O Chatbot "fala" (imprime a resposta)
    print("\n[chatbot]:", result['answer'])



"""##**2. Processo final**

Desenvolva aqui:
"""

!pip install langchain langchain-openai langchain_community pypdf chromadb tiktoken faiss-cpu gdown --quiet

## ==============================================================================
## SEÇÃO 2: PROCESSO FINAL (TUDO EM UMA CÉLULA)
## ==============================================================================

## --- 1. Importações necessárias ---
import os
import gdown
from google.colab import userdata
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
    MessagesPlaceholder
)
import warnings

# Ignorar avisos de depreciação do LangChain (opcional, mas limpa o output)
warnings.filterwarnings("ignore")

## --- 2. Definição de Todas as Funções ---

def baixar_documento_contexto():
    """Baixa o arquivo PDF do Google Drive."""
    file_id = "1-ZpUOl8OA4lxa8CJ6auT42hSxaF3jclk"
    local_filename = "iAutos_Politicas_e_Uso.pdf"
    print(f"\n📥 Baixando arquivo de contexto: {local_filename}")
    try:
        gdown.download(f"https://drive.google.com/uc?id={file_id}", local_filename, quiet=True)
        print("✅ Arquivo baixado com sucesso.")
        return local_filename
    except Exception as e:
        print(f"❌ Erro ao baixar o arquivo: {e}")
        return None

def preparar_documentos(pdf_path):
    """Carrega o PDF e divide em chunks."""
    if not pdf_path:
        return []
    print("\n📄 Carregando e fatiando o documento...")
    loader = PyPDFLoader(pdf_path)
    documents_pdf = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len,
    )
    chunks = text_splitter.split_documents(documents_pdf)
    print(f"✅ Documento dividido em {len(chunks)} fragmentos.")
    return chunks

def criar_vectordb(chunks):
    """Cria o ChromaDB usando Azure Embeddings (com Secrets)."""
    print("\n🧠 Criando o VectorDB (ChromaDB) com Azure Embeddings...")
    os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
    os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

    embeddings = AzureOpenAIEmbeddings(
        azure_deployment=userdata.get('EMB_DEPLOYMENT_MODEL'),
        openai_api_version=userdata.get('EMB_API_VERSION')
    )
    vectordb = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        collection_name="iAutos_politicas"
    )
    print("✅ ChromaDB criado e pronto para recuperação (Retriever).")
    return vectordb

def construir_chatbot_chain(vectordb):
    """Constrói o ChatBot com LLM, Memória e o Prompt corrigido."""
    print("\n🤖 Construindo o Chatbot (ConversationalRetrievalChain)...")

    os.environ["AZURE_OPENAI_ENDPOINT"] = userdata.get('AZURE_OPENAI_ENDPOINT')
    os.environ["AZURE_OPENAI_API_KEY"] = userdata.get('AZURE_OPENAI_API_KEY')

    llm = AzureChatOpenAI(
        azure_deployment=userdata.get('LLM_DEPLOYMENT_MODEL'),
        openai_api_version=userdata.get('LLM_API_VERSION'),
        temperature=0.3
    )

    memory = ConversationBufferMemory(
        memory_key="chat_history",
        return_messages=True,
        output_key="answer"
    )

    # --- PROMPT COMPATÍVEL COM STUFFDOCUMENTSCHAIN ---
    from langchain.prompts import PromptTemplate

    SYSTEM_TEMPLATE = """
Você é o ChatBot de Atendimento da iAutos, um marketplace de classificados de veículos.
Sua missão é responder perguntas dos clientes de forma precisa, educada e SOMENTE com base no contexto
fornecido abaixo, que contém as políticas de uso e regras de publicação de veículos da iAutos.

Diretrizes de Resposta:
- Responda SOMENTE com informações encontradas no contexto recuperado.
- Se o contexto **não contiver** a resposta, diga EXATAMENTE:
  "Desculpe, a informação exata sobre este tópico não está detalhada nas Políticas de Uso da iAutos que eu tenho acesso."
- Nunca invente ou faça suposições, mesmo que a pergunta pareça simples.
- Mantenha o tom de voz profissional, educado e prestativo.

Contexto:
{context}

Pergunta:
{question}
"""

    qa_prompt = PromptTemplate(
        template=SYSTEM_TEMPLATE,
        input_variables=["context", "question"]
    )

    qa_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vectordb.as_retriever(search_kwargs={"k": 3}),
        memory=memory,
        combine_docs_chain_kwargs={"prompt": qa_prompt},
        return_source_documents=True,
        output_key="answer"
    )

    print("✅ ChatBot pronto!")
    return qa_chain

def simular_conversa(qa_chain):
    """
    Loop de conversação para interagir com o ChatBot.
    AGORA COM O ROTEADOR INTELIGENTE.
    """
    print("\n\n--- 🤖 SIMULADOR DE CHATBOT iAutos (Versão Robusta) ---")
    print("Digite 'sair' a qualquer momento para encerrar.\n")

    # A memória já está dentro da qa_chain, então não precisamos
    # gerenciar o histórico aqui fora.

    while True:
        try:
            query = input("[VOCÊ]: ")
            if query.lower() in ["sair", "exit", "tchau", "fim", "encerrar"]:
                print("\n[CHATBOT]: Até logo! Obrigado por usar a iAutos.")
                break

            # --- ROTEADOR INTELIGENTE (A lógica do teste) ---
            q_lower = query.lower()
            if any(palavra in q_lower for palavra in ["preço", "valor", "quanto custa", "gol", "caro", "barato"]):
                # AÇÃO A: Responde com a regra de negócio
                print("\n[CHATBOT]: A iAutos não define preços de veículos. Os valores variam conforme os anúncios de vendedores. Consulte a barra de busca da plataforma para ver os preços atualizados.")

            else:
                # AÇÃO B: Usa o RAG para perguntas de política
                result = qa_chain.invoke({"question": query})
                print("\n[CHATBOT]:", result['answer'])
            # --- FIM DO ROTEADOR ---

        except Exception as e:
            print(f"\n[CHATBOT]: Ops, houve um erro inesperado. Erro: {e}")
            break # Encerra o loop em caso de erro# Encerra o loop em caso de erro

def rodar_pipeline_completo():
    """Executa todas as etapas do processo final."""

    # A instalação foi movida para a célula anterior

    pdf_path = baixar_documento_contexto()
    if pdf_path:
        chunks = preparar_documentos(pdf_path)
        if chunks:
            vectordb = criar_vectordb(chunks)
            qa_chain = construir_chatbot_chain(vectordb)
            simular_conversa(qa_chain)
        else:
            print("❌ Erro: Nenhum fragmento (chunk) foi criado do PDF.")
    else:
        print("❌ Erro: O download do PDF falhou. O pipeline não pode continuar.")

## --- 3. Execução Imediata ---
# (Roda o pipeline assim que esta célula é executada)
rodar_pipeline_completo()

"""# Exemplos de Conversa

--- 🤖 SIMULADOR DE CHATBOT iAutos ---
Digite 'sair' a qualquer momento para encerrar.

[VOCÊ]: Quais são os tipos de veículos permitidos?

[CHATBOT]: Os tipos de veículos permitidos na iAutos são:

- Passageiros: automóveis (sedan, hatch, SUV, picape, minivan), van, furgão, micro-ônibus, ônibus, motonetas, motocicletas, triciclos e quadriciclos.
- Carga: utilitários, caminhões e camionetas.
- Motorização: veículos de combustão, elétricos e híbridos.

[VOCÊ]: E sobre as motos, quais as regras?

[CHATBOT]: Na iAutos, é permitido anunciar motonetas, motocicletas, triciclos e quadriciclos. No entanto, ciclomotores (veículos de duas ou três rodas com até 50 cm³ ou equivalente elétrico e velocidade máxima de até 50 km/h) são proibidos.

Além disso, nas fotos ou descrições dos anúncios, não é permitido incluir números de telefone, celular, WhatsApp, e-mails ou endereços de localização (logradouros).

[VOCÊ]: Qual o preço médio de um Gol ?

[CHATBOT]: Desculpe, a informação exata sobre este tópico não está detalhada nas Políticas de Uso da iAutos que eu tenho acesso.

[VOCÊ]: Como eu entro em contato com o vendedor?

[CHATBOT]: O contato entre comprador e vendedor na iAutos só é liberado pela plataforma após solicitação de interesse (lead) pelo comprador. Portanto, primeiro é necessário demonstrar interesse no veículo pela plataforma; após isso, o contato será disponibilizado.

[VOCÊ]: O que acontece se eu tentar fraudar a plataforma?

[CHATBOT]: Se você tentar fraudar a plataforma iAutos, a punição aplicada é o banimento permanente da conta.

[VOCÊ]: sair

[CHATBOT]: Até logo! Obrigado por usar a iAutos.
"""